[workspace]
resolver = "2"
members = ["crates/core", "crates/desktop", "crates/ui"]
default-members = ["crates/desktop"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
dirs = "6"
magenta-core = { path = "crates/core" }
magenta-ui = { path = "crates/ui" }
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = [
  "font-kit",
  "wayland",
  "x11",
] }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "49229371e095bfd2ca77d336b5972b16956f0a87" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "49229371e095bfd2ca77d336b5972b16956f0a87" }
thiserror = "2"
tracing = "0.1"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
