[package]
name = "magenta-providers"
version.workspace = true
edition.workspace = true

[dependencies]
async-lock.workspace = true
async-net.workspace = true
async-stream.workspace = true
base64.workspace = true
futures-util.workspace = true
http_client.workspace = true
keyring.workspace = true
magenta-core.workspace = true
reqwest_client.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
smol.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
