[package]
name = "magenta-ui"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
anyhow.workspace = true
futures-util.workspace = true
magenta-application.workspace = true
magenta-core.workspace = true
gpui.workspace = true
gpui-base.workspace = true
gpui-component.workspace = true
parking_lot.workspace = true
ratex-layout.workspace = true
ratex-parser.workspace = true
ratex-svg.workspace = true
ratex-types.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
futures-channel.workspace = true
gpui = { workspace = true, features = ["test-support"] }
