[package]
name = "magenta-desktop"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "magenta"
path = "src/main.rs"

[dependencies]
dirs.workspace = true
magenta-application.workspace = true
magenta-core.workspace = true
magenta-providers.workspace = true
magenta-storage.workspace = true
magenta-ui.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
